# ── 로컬 (WSL2) ──────────────────────────────────────────────────────────────
[local]
localhost ansible_connection=local

# ── Airflow VM ───────────────────────────────────────────────────────────────
[airflow]
airflow-vm ansible_host=192.168.253.149 ansible_user=ubuntu ansible_ssh_pass=ubuntu ansible_become_pass=ubuntu

# ── 백엔드 서버 (현재는 WSL2 로컬) ───────────────────────────────────────────
[backend]
localhost ansible_connection=local

# ── 전체 그룹 ─────────────────────────────────────────────────────────────────
[invest_flow:children]
local
airflow

# ── Gitlab VM ───────────────────────────────────────────────────────────────
[gitlab]
gitlab-vm ansible_host=192.168.253.148 ansible_user=ubuntu ansible_ssh_pass=ubuntu ansible_become_pass=ubuntu